apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-gen-model
  namespace: argo
spec:
  service:
    ports:
    - port: 8086
      targetPort: 8086
  webhook: 
    webhook-gen-model:
      endpoint: /deploy
      method: POST
      port: "8086"
      url: ""